name: hizip
description: Finder-inspired archive manager with a native libarchive engine.
publish_to: none
version: 0.1.0+1
environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  file_selector: ^1.1.0
  path_provider: ^2.1.5
  path: ^1.9.1
  crypto: ^3.0.6
  open_filex: ^4.7.0
  hizip_native:
    path: packages/hizip_native
  super_drag_and_drop: ^0.9.1
  super_clipboard: ^0.9.1
  forui: ^0.21.3
  nativeapi_flutter: ^0.4.1
  desktop_multi_window: ^0.3.1
  shared_preferences: ^2.5.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  cnativeapi:
    path: packages/cnativeapi

flutter:
  uses-material-design: true
