/// Shared by native file pickers, creation menus and drag-to-open handling.
const readableArchiveExtensions = [
  'zip',
  '7z',
  'rar',
  'tar',
  'gz',
  'bz2',
  'xz',
  'lzma',
  'tgz',
  'tbz',
  'tbz2',
  'txz',
  'tlz',
  'z',
  'zst',
  'lz4',
  'lz',
  'cpio',
  'cab',
  'iso',
  'xar',
  'rpm',
  'deb',
  'ar',
  'a',
  'lha',
  'lzh',
  'jar',
  'war',
  'cbz',
  'epub',
];
const writableArchiveFormats = <String, String>{
  'zip': 'ZIP',
  '7z': '7z',
  'tar': 'TAR',
  'tar.gz': 'TAR + gzip',
  'tar.bz2': 'TAR + bzip2',
  'tar.xz': 'TAR + xz',
  'tar.lzma': 'TAR + LZMA',
  'cpio': 'CPIO',
  'gz': 'gzip（单个文件）',
  'bz2': 'bzip2（单个文件）',
  'xz': 'xz（单个文件）',
  'lzma': 'LZMA（单个文件）',
};
