/// Shared by native file pickers, creation menus and drag-to-open handling.
const readableArchiveExtensions = [
  'zip',
  'zip.001',
  '7z.001',
  '7z',
  'rar',
  'tar',
  'gz',
  'bz2',
  'xz',
  'lzma',
  'tgz',
  'tbz',
  'tbz2',
  'txz',
  'tlz',
  'tar.zst',
  'tzst',
  'tar.lz4',
  'tlz4',
  'tar.lzip',
  'tlzip',
  'tar.Z',
  'z',
  'zst',
  'lz4',
  'lzip',
  'lz',
  'cpio',
  'cab',
  'iso',
  'xar',
  'rpm',
  'deb',
  'ar',
  'a',
  'lha',
  'lzh',
  'jar',
  'war',
  'cbz',
  'epub',
];

final readableArchivePickerExtensions = [
  ...readableArchiveExtensions,
  for (final letter in ['r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'])
    for (var number = 0; number < 100; number++)
      '$letter${number.toString().padLeft(2, '0')}',
];

bool isReadableArchivePath(String path) {
  final lowerPath = path.toLowerCase();
  if (RegExp(r'\.(zip|7z)\.\d{3,}$').hasMatch(lowerPath)) return true;
  if (RegExp(r'\.[r-z]\d{2}$').hasMatch(lowerPath)) return true;
  return readableArchiveExtensions.any(
    (extension) => lowerPath.endsWith('.${extension.toLowerCase()}'),
  );
}

const readableArchiveMimeTypes = [
  'application/zip',
  'application/x-7z-compressed',
  'application/vnd.rar',
  'application/x-rar-compressed',
  'application/x-tar',
  'application/x-compressed-tar',
  'application/gzip',
  'application/x-gzip',
  'application/x-bzip2',
  'application/x-bzip',
  'application/x-bzip-compressed-tar',
  'application/x-xz',
  'application/x-xz-compressed-tar',
  'application/x-lzma',
  'application/x-lzip',
  'application/x-zstd-compressed-tar',
  'application/x-lz4-compressed-tar',
  'application/x-lzip-compressed-tar',
  'application/zstd',
  'application/x-zstd',
  'application/x-lz4',
  'application/x-lzip',
  'application/x-cpio',
  'application/vnd.ms-cab-compressed',
  'application/x-iso9660-image',
  'application/x-xar',
  'application/x-rpm',
  'application/vnd.debian.binary-package',
  'application/x-archive',
  'application/x-lha',
  'application/x-lzh',
  'application/java-archive',
  'application/epub+zip',
  'application/vnd.comicbook+zip',
];

const writableArchiveFormats = <String, String>{
  'zip': 'ZIP',
  '7z': '7z',
  'tar': 'TAR',
  'tar.gz': 'TAR + gzip',
  'tar.bz2': 'TAR + bzip2',
  'tar.xz': 'TAR + xz',
  'tar.lzma': 'TAR + LZMA',
  'tar.zst': 'TAR + zstd',
  'tar.lz4': 'TAR + LZ4',
  'tar.lzip': 'TAR + lzip',
  'tar.Z': 'TAR + compress',
  'cpio': 'CPIO',
  'ar': 'ar archive',
  'gz': 'gzip（单个文件）',
  'bz2': 'bzip2（单个文件）',
  'xz': 'xz（单个文件）',
  'lzma': 'LZMA（单个文件）',
  'zst': 'zstd（单个文件）',
  'lz4': 'LZ4（单个文件）',
  'lzip': 'lzip（单个文件）',
  'Z': 'compress（单个文件）',
};
