name: hizip_native
description: Native streaming archive operations using libarchive.
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
        pluginClass: HizipNativePlugin
      windows:
        ffiPlugin: true
